export { createBrowserCanvasClient } from './browser-client.js'
export type { BrowserCanvasClientHandle, BrowserCanvasClientOptions } from './browser-client.js'
export { CanvasRenderer, enableSelection, enableFind, enableAccessibilityMirror, enableInputForwarding } from './renderer.js'
export type { CanvasRendererOptions, AccessibilityMirrorOptions, CanvasInputForwardingOptions } from './renderer.js'
export { attachGestureRecognizers } from './gestures.js'
export type { AttachGestureRecognizersOptions, CanvasGestureRecognizerLike } from './gestures.js'
